name: Integration Tests

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'

      - uses: actions/checkout@v4

      - name: Run tests
        run: dart test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies using the Puro Sidekick Plugin
        run: cd ci_test && ./skt flutter pub get